name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: ./build-and-test.sh
    - uses: actions/upload-artifact@v4
      with:
        name: calc
        path: ./dist
